"""Build DubtrackrAutoClicker.exe with PyInstaller.

    pip install -r requirements-build.txt
    python build.py

Produces dist/DubtrackrAutoClicker.exe (single file, windowed, branded icon).
"""
import os
import subprocess
import sys
import tempfile

from version import VERSION, VERSION_TUPLE

HERE = os.path.dirname(os.path.abspath(__file__))


def version_info_text():
    """Return the PyInstaller Windows version resource from the canonical version."""
    return f"""# Generated by build.py from version.py; do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={VERSION_TUPLE},
    prodvers={VERSION_TUPLE},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'Dubtrackr'),
            StringStruct('FileDescription', 'DubTrackr AutoClickr'),
            StringStruct('FileVersion', '{VERSION}.0'),
            StringStruct('InternalName', 'DubTrackrAutoClickr'),
            StringStruct('LegalCopyright', '© 2026 Dubtrackr. MIT License.'),
            StringStruct('OriginalFilename', 'DubtrackrAutoClicker.exe'),
            StringStruct('ProductName', 'DubTrackr AutoClickr'),
            StringStruct('ProductVersion', '{VERSION}.0'),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def main():
    import customtkinter
    ctk_dir = os.path.dirname(customtkinter.__file__)
    sep = ";" if os.name == "nt" else ":"

    with tempfile.TemporaryDirectory(prefix="dubtrackr-autoclicker-") as temp_dir:
        version_file = os.path.join(temp_dir, "version_info.txt")
        with open(version_file, "w", encoding="utf-8") as handle:
            handle.write(version_info_text())

        cmd = [
            sys.executable, "-m", "PyInstaller",
            "--noconfirm", "--clean", "--onefile", "--windowed",
            "--name", "DubtrackrAutoClicker",
            "--icon", os.path.join(HERE, "dubtrackr.ico"),
            "--version-file", version_file,
            "--add-data", f"{os.path.join(HERE, 'dubtrackr.ico')}{sep}.",
            "--add-data", f"{os.path.join(HERE, 'assets')}{sep}assets",
            "--add-data", f"{ctk_dir}{sep}customtkinter",
            "--collect-submodules", "customtkinter",
            # numpy is dragged in by Pillow but never used — ~28 MB of dead weight
            "--exclude-module", "numpy",
            os.path.join(HERE, "dubtrackr_autoclicker.py"),
        ]
        print(" ".join(cmd))
        subprocess.check_call(cmd)
    print("\nDone -> dist/DubtrackrAutoClicker.exe")


if __name__ == "__main__":
    main()
